name: Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags (e.g., v0.1.0)

jobs:
  build:
    name: Build & Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: langscan-linux-amd64
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: langscan-macos-amd64
          - os: macos-14 # Apple Silicon runner
            target: aarch64-apple-darwin
            artifact_name: langscan-macos-arm64

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }} && mkdir -p dist && cp target/${{ matrix.target }}/release/langscan dist/${{ matrix.artifact_name }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/${{ matrix.artifact_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/**/*
          generate_release_notes: true
